Traceback (most recent call last):
  File "/share/lab_goecks/TCGA_deep_learning/tcga_manuscript/tiles_embedding_test/pytorch/galaxy_tool/vgg/pytorch_test_xvalidation.py", line 301, in <module>
    main()
  File "/share/lab_goecks/TCGA_deep_learning/tcga_manuscript/tiles_embedding_test/pytorch/galaxy_tool/vgg/pytorch_test_xvalidation.py", line 289, in main
    metric_values = {key: [m[key] for m in fold_metrics[split_key]] for key in metrics_keys}
  File "/share/lab_goecks/TCGA_deep_learning/tcga_manuscript/tiles_embedding_test/pytorch/galaxy_tool/vgg/pytorch_test_xvalidation.py", line 289, in <dictcomp>
    metric_values = {key: [m[key] for m in fold_metrics[split_key]] for key in metrics_keys}
KeyError: 'validation'
